import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='w-full h-screen'>
        <header className='fixed p-10 pb-0 z-10 max-md:p-2'>
          <Link href='/'>
            <Image
              src='/images/deg_logo.png'
              alt='로고'
              width={100}
              height={150}
            />
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
