import LoginBtn from '@/component/LoginBtn';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='bg-black'>
        <header className='fixed w-full flex items-center p-12'>
          <Link href='/'>
            <Image
              src='/images/deg_logo.png'
              alt='로고'
              width={100}
              height={150}
            />
          </Link>

          {/* 로그인 버튼 */}
          <LoginBtn />
        </header>
        {children}

        <footer className='fixed right-16 bottom-14'>
          <button className='text-gray-200 border rounded-md border-gray-200 px-6 py-4 hover:bg-gray-50 hover:text-gray-600 transition-all'>
            당신의 저녁을 공유해주세요
          </button>
        </footer>
      </body>
    </html>
  );
}
